---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
  default: now
- type: number
  name: weight
  label: weight
  default: '1'
- type: file
  name: thumbnail
  label: thumbnail
- type: image_gallery
  name: gallery
  label: gallery
pages:
- content/projects/adventure.md
- content/projects/bom-tempo.md
- content/projects/allons-y.md
- content/projects/first-turnabout.md
- content/projects/bear-hug.md
- content/projects/cobogó.md
- content/projects/bnp-paribas-brochure.md
