---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: number
  name: weight
  label: weight
- type: file
  name: thumbnail
  label: thumbnail
- type: image_gallery
  name: gallery
  label: gallery
